/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { Addr } from "../../../modules/shared";

export type QueryMsg =
  | GetContest
  | GetContests
  | GetActiveContests
  | GetUserBet
  | GetUsersBets
  | GetMinBet
  | GetSnip20
  ;

export interface GetContest {
  get_contest: {
    contest_id: string;
    [k: string]: unknown;
  };
}
export interface GetContests {
  get_contests: {
    contest_ids: string[];
    [k: string]: unknown;
  };
}
export interface GetActiveContests {
  get_active_contests: {
    page_num?: number | null;
    page_size?: number | null;
    sort_order?: ContestQuerySortOrder | null;
    [k: string]: unknown;
  };
}
export interface GetUserBet {
  get_user_bet: {
    contest_id: string;
    user: Addr;
    viewing_key: string;
    [k: string]: unknown;
  };
}
export interface GetUsersBets {
  get_users_bets: {
    filters?: UsersBetsQueryFilters[] | null;
    user: Addr;
    viewing_key: string;
    [k: string]: unknown;
  };
}
export interface GetMinBet {
  get_min_bet: {
    [k: string]: unknown;
  };
}
export interface GetSnip20 {
  get_snip20: {
    [k: string]: unknown;
  };
}


export type ContestQuerySortOrder = "volume";
export type UsersBetsQueryFilters = "claimable";
