/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { ContractInfo, Uint128 } from "../../../modules/shared";
import { Bet, ContestBetSummary, ContestInfo } from "./common_types";

export type QueryResponse =
  | ContestDataResponse
  | ContestDataListResponse
  | UserBetResponse
  | UsersBetsResponse
  | MinimumBetResponse
  | GetSnip20Response
  ;



export interface ContestDataResponse {
  contest_data: {
    contest_bet_summary: ContestBetSummary;
    contest_info: ContestInfo;
    [k: string]: unknown;
  };
}


export interface ContestDataListResponse {
  contest_data_list: {
    contests: ContestDataResponse[];
    [k: string]: unknown;
  };
}
export interface UserBetResponse {
  user_bet: {
    bet: Bet;
    [k: string]: unknown;
  };
}
export interface UsersBetsResponse {
  users_bets: {
    contests_bets: UserContestBetInfo[];
    [k: string]: unknown;
  };
}

export interface MinimumBetResponse {
  minimum_bet: {
    minimum_bet: Uint128;
    [k: string]: unknown;
  };
}
export interface GetSnip20Response {
  snip20: {
    snip20: ContractInfo;
    [k: string]: unknown;
  }
  ;
}


export interface UserContestBetInfo {
  contest_bet_summary: ContestBetSummary;
  contest_info: ContestInfo;
  user_bet: Bet;
  [k: string]: unknown;
}