/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { Addr, Binary, Uint128 } from "../../../modules/shared/contract/types";


export type ExecuteMsg =
  | {
    receive: {
      amount: Uint128;
      from: Addr;
      memo?: string | null;
      msg: Binary;
      sender: Addr;
      [k: string]: unknown;
    };
  }
  | {
    receive_nft: {
      /**
       * optional message to control receiving logic
       */
      msg?: Binary | null;
      /**
       * previous owner of sent token
       */
      sender: Addr;
      /**
       * token that was sent
       */
      token_id: string;
      [k: string]: unknown;
    };
  };
