/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { Uint128 } from "../../../modules/shared/contract/types";


export type QueryAnswer =
  | ContractBalanceAnswer
  | SingleNftPriceAnswer
  | AllNftPricesAnswer;


export interface ContractBalanceAnswer {
  contract_balance: Balance;
}
export interface SingleNftPriceAnswer {
  nft_price: NftPriceAnswer;
}
export interface AllNftPricesAnswer {
  nft_prices: NftPriceAnswer[];
}
/**
 * response for [`AllTokens`](QueryMsg::AllTokens) and [`Tokens`](QueryMsg::Tokens)
 *
 * * AllTokens: display an optionally paginated list of all the tokens controlled by the contract. The token supply must either be public, or the querier must be authorized to view * Tokens: displays a list of all the tokens belonging to the input owner in which the viewer has view_owner permission
 */
export interface TokenList {
  /**
   * list of token IDs
   */
  tokens: string[];
  [k: string]: unknown;
}
/**
 * Balance response
 */
export interface Balance {
  amount: Uint128;
  [k: string]: unknown;
}
export interface NftPriceAnswer {
  price: Uint128;
  token_id: string;
  [k: string]: unknown;
}

