/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */


export type QueryMsg =
  | AllNftPricesQuery
  | ContractBalanceQuery
  | NftPriceQuery
  ;
export interface AllNftPricesQuery {
  all_nft_prices: {
    [k: string]: unknown;
  };
}
export interface ContractBalanceQuery {
  contract_balance: {
    [k: string]: unknown;
  };
}
export interface NftPriceQuery {
  nft_price: {
    token_id: string;
    [k: string]: unknown;
  }
}