/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type QueryMsg =
  | {
      get_result: GetResult;
    }
  | {
      get_detailed_result: GetResult;
    }
  | {
      get_providers: GetProviders;
    }
  | {
      get_owner: GetOwner;
    };

export interface GetResult {
  id: string;
  [k: string]: unknown;
}
export interface GetProviders {
  [k: string]: unknown;
}
export interface GetOwner {
  [k: string]: unknown;
}
