/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { Addr } from "../../shared";

export type ExecuteMsg =
  | PostResult
  | AddProvider
  | RemoveProvider;

export interface PostResult {
  post_result: {
    id: string;
    result_value: number;
    [k: string]: unknown;
  };
}
export interface AddProvider {
  add_provider: {
    provider: Addr;
    [k: string]: unknown;
  };
}
export interface RemoveProvider {
  remove_provider: {
    provider: Addr;
    [k: string]: unknown;
  };
}