/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ExecuteResponse = PostResultResponse;

export type ResponseStatus = "success" | "failure";

export interface PostResultResponse {
  post_result: {
    status: ResponseStatus;
    [k: string]: unknown;
  };
};