/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { Addr } from "../../shared";

export type QueryResponse =
  | ListProvidersResponse
  | GetResultResponse
  | GetDetailedResultResponse
  | GetOwnerResponse

export interface ListProvidersResponse {
  list_providers_response: {
    providers: Addr[];
    [k: string]: unknown;
  };
}
export interface GetOwnerResponse {
  get_owner_response: {
    owner: Addr;
    [k: string]: unknown;
  };
};
export interface GetResultResponse {
  get_result_response: {
    result: number;
    [k: string]: unknown;
  };
};
export interface GetDetailedResultResponse {
  get_detailed_result_response: {
    result: Result;
    [k: string]: unknown;
  };
};
export interface Result {
  id: string;
  order_id: number;
  provider: Addr;
  result: number;
  [k: string]: unknown;
}
