/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type QueryMsg =
  | GetContestResult
  | GetDetailedResult
  | GetProviders
  | GetOwner

export interface GetContestResult {
  get_contest_result: {
    id: string;
    [k: string]: unknown;
  };
}
export interface GetDetailedResult {
  get_detailed_result: {
    id: string;
    [k: string]: unknown;
  };
}
export interface GetProviders {
  get_providers: {
    [k: string]: unknown;
  };
}
export interface GetOwner {
  get_owner: {
    [k: string]: unknown;
  };
};