/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { Binary, Uint128 } from "../../../shared/contract/types";
import { TokenAmount, TokenType } from "../../common_types";
import { Hop } from "./common_types";

export type ExecuteMsg =
  | Receive_msg
  | Swap_tokens_for_exact_msg
  | Register_s_n_i_p20_token_msg
  | Recover_funds_msg
  ;


export interface Receive_msg {
  receive: {
    amount: Uint128;
    from: string;
    msg?: Binary | null;
    [k: string]: unknown;
  };
}
export interface Swap_tokens_for_exact_msg {
  swap_tokens_for_exact: {
    expected_return?: Uint128 | null;
    /**
     * The token type to swap from.
     */
    offer: TokenAmount;
    path: Hop[];
    recipient?: string | null;
    [k: string]: unknown;
  };
}
export interface Register_s_n_i_p20_token_msg {
  register_s_n_i_p20_token: {
    token_addr: string;
    token_code_hash: string;
    [k: string]: unknown;
  };
}
export interface Recover_funds_msg {
  recover_funds: {
    amount: Uint128;
    msg?: Binary | null;
    to: string;
    token: TokenType;
    [k: string]: unknown;
  };
}