/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { Binary, ContractInfo } from "../../../shared/contract/types";


export interface InitMsg {
  admin_auth: ContractInfo;
  entropy: Binary;
  prng_seed: Binary;
  [k: string]: unknown;
}
