/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { Uint128, ContractInfo } from "../../../shared/contract/types";
import { SwapResult } from "../../common_types";

export type QueryMsgResponse =
  | Swap_simulation_response
  | Get_config_response
  ;

// Individual queries
export interface Swap_simulation_response {
  swap_simulation: {
    lp_fee_amount: Uint128;
    price: string;
    result: SwapResult;
    shade_dao_fee_amount: Uint128;
    total_fee_amount: Uint128;
    [k: string]: unknown;
  };
}
export interface Get_config_response {
  get_config: {
    admin_auth: ContractInfo;
    [k: string]: unknown;
  };
}
