/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { Addr } from "../../../modules/shared";

export type QueryMsg =
  | Is_viewing_key_valid_query
  | Assert_viewing_key_valid_query
  ;


export interface Is_viewing_key_valid_query {
  is_viewing_key_valid: {
    address: Addr;
    viewing_key: string;
    [k: string]: unknown;
  };
}

export interface Assert_viewing_key_valid_query {
  assert_viewing_key_is_valid: {
    address: Addr;
    viewing_key: string;
    [k: string]: unknown;
  };
}
