/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { Binary, Uint128, ContractInfo } from "../../../shared/contract/types";
import { TokenType } from "../../common_types";

export type ExecuteMsg =
  | Claim_rewards_msg
  | Proxy_unstake_msg
  | Unstake_msg
  | Receive_msg
  | Set_reward_token_msg
  | Set_authenticator_msg
  | Set_config_msg
  | Recover_funds_msg
  ;



export interface Claim_rewards_msg {
  claim_rewards: {
    [k: string]: unknown;
  };
}
export interface Proxy_unstake_msg {
  proxy_unstake: {
    amount: Uint128;
    for_addr: string;
    [k: string]: unknown;
  };
}
export interface Unstake_msg {
  unstake: {
    amount: Uint128;
    remove_liquidity?: boolean | null;
    [k: string]: unknown;
  };
}
export interface Receive_msg {
  receive: {
    amount: Uint128;
    from: string;
    msg?: Binary | null;
    [k: string]: unknown;
  };
}
export interface Set_reward_token_msg {
  set_reward_token: {
    daily_reward_amount: Uint128;
    reward_token: TokenType;
    valid_to: Uint128;
    [k: string]: unknown;
  };
}
export interface Set_authenticator_msg {
  set_authenticator: {
    authenticator?: ContractInfo | null;
    [k: string]: unknown;
  };
}
export interface Set_config_msg {
  set_config: {
    admin_auth?: ContractInfo | null;
    [k: string]: unknown;
  };
}
export interface Recover_funds_msg {
  recover_funds: {
    amount: Uint128;
    msg?: Binary | null;
    to: string;
    token: TokenType;
    [k: string]: unknown;
  };
}
