/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { Binary, Uint128, ContractInfo } from "../../../../modules/shared/contract/types";
import { TokenType } from "../../common_types";


export interface InitMsg {
  admin_auth: ContractInfo;
  authenticator?: ContractInfo | null;
  daily_reward_amount: Uint128;
  lp_token: ContractInfo;
  pair_contract: ContractInfo;
  prng_seed: Binary;
  reward_token: TokenType;
  valid_to: Uint128;
  [k: string]: unknown;
}
