/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { Uint128, ContractInfo } from "../../../shared/contract/types";
import { TokenType } from "../../common_types";

export type QueryResponse =
  | Get_claim_reward_response
  | Get_staker_lp_token_info_response
  | Get_config_response
  | Get_reward_tokens_response
  ;

// Individual responses
export interface Get_claim_reward_response {
  get_claim_reward: {
    claimable_rewards: ClaimableInfo[];
    [k: string]: unknown;
  };
}
export interface Get_staker_lp_token_info_response {
  get_staker_lp_token_info: {
    staked_lp_token: Uint128;
    total_staked_lp_token: Uint128;
    [k: string]: unknown;
  };
}
export interface Get_config_response {
  get_config: {
    admin_auth: ContractInfo;
    amm_pair: string;
    lp_token: ContractInfo;
    reward_token: ContractInfo;
    total_staked_lp_token: Uint128;
    [k: string]: unknown;
  };
}
export interface Get_reward_tokens_response {
  get_reward_tokens: {
    tokens: RewardTokenInfo[];
    [k: string]: unknown;
  };
}



// Base Types
export interface ClaimableInfo {
  amount: Uint128;
  token_address: string;
  [k: string]: unknown;
}

export interface RewardTokenInfo {
  last_update_time: Uint128;
  reward_per_token_stored: Uint128;
  reward_rate: Uint128;
  reward_token: TokenType;
  valid_to: Uint128;
  [k: string]: unknown;
}
